name: 'Run Lint'

on: [push, pull_request]

jobs:
  run-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: Set up yarn
        run: yarn install

      - name: Run prettier
        run: yarn run format

      - name: Run lint
        run: yarn run lint
